SELECT COUNT(*) N_AISLE_COUNT FROM G5CMPE295.N_AISLE;
SELECT COUNT(*) N_OFFERS_COUNT FROM G5CMPE295.N_OFFERS;
SELECT COUNT(*) N_PROD_STORE_COUNT FROM G5CMPE295.N_PROD_STORE;
SELECT COUNT(*) N_SENSOR_COUNT FROM G5CMPE295.N_SENSORS;
SELECT COUNT(*) N_STORE_COUNT FROM G5CMPE295.N_STORE;

SELECT COUNT(*) N_CUSTOMER_COUNT FROM G5CMPE295.N_CUSTOMER;
SELECT COUNT(*) N_PRODUCT_COUNT FROM G5CMPE295.N_PRODUCT;
SELECT COUNT(*) N_PROD_CLASS_COUNT FROM G5CMPE295.N_PRODUCT_CLASS;
SELECT COUNT(*) N_SALES_COUNT FROM G5CMPE295.N_SALES_FACT_1997;
SELECT COUNT(*) N_TIMEBYDAY_COUNT FROM G5CMPE295.N_TIME_BY_DAY;
SELECT COUNT(*) N_POSTXN_COUNT FROM G5CMPE295.N_POS_TXN;

